### PR TITLE
Update recipe for tofu 1.4.8

### PR DESCRIPTION
**Pull request by flothesof**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flothesof** [comment]
@conda-forge-admin, please rerender

**Comment by Didou09** [comment]
Hum, there seems to be a windows-specific error...
@flothesof, @lasofivec , I opened a dedicated issue, in the meantime, do you think we should force-merge to conda forge even if don't have windows platform supported or wait until the issue is fixed and do another release later ?

It is annoying because 1.4.8 is kind of half-released: it is on conda (on ToFuProject channel) and on Pypi, but not on conda-forge just because of windows...

**Comment by lasofivec** [comment]
I am trying to catch up on how it works with conda-forge. Now that buf-fix has been merged is it possible to re submit this release ? Or the release number hast to change?

**Comment by flothesof** [comment]
> I am trying to catch up on how it works with conda-forge. Now that buf-fix has been merged is it possible to re submit this release ? Or the release number hast to change?

The way conda-forge works is as follows:

download sdist from pypi --> generate conda package (see https://github.com/conda-forge/tofu-feedstock/blob/d239c6ac12222a9f09f3061bd2c38385892eded3/recipe/meta.yaml#L9)

In theory it is possible to resubmit a conda-forge build by changing its version number, but this would download the same sdist so the results won't change.
Another option is to use a patch that allows to change the source code in the conda-forge build (there is one in the conda forge build disabling openmp by the way). But since the source has already been fixed, the best option in my opinion is to make a new pypi release and then do a new conda forge build on the new sdist.

**Comment by Didou09** [comment]
OK, if everyone agrees, I'll release 1.4.9 with Florian's hotfix
@lasofivec fine for you too ?

**Comment by lasofivec** [comment]
ok, we need to add a windows testing to our CI before future release though...

**Comment by Didou09** [comment]
Yes probably... That might mean switching from Travis to something else though, like Microsoft (aka the devil) Windows (beurk) Azure... but Github is Microsoft already so I guess our souls are bound to go to hell anyway...
Other suggestions ?

P.S.: I'm using this new 1.4.9 to merge a new mini-branch with small changes I had forgotten to do.
Shall be operational this evening.

**Comment by lasofivec** [comment]
I know travis has been working on windows + python support.
I want to try something tomorrow:
https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci

May I have till the end of the week to see how it goes ? If it works we can stay with Travis ftm at least

**Comment by flothesof** [comment]
closed by auto-pr from conda-forge bot #8 (apparently no need to do this manually yay!)

**Pull request closed without merging**
