### PR TITLE
update tofu to 1.5.2 from flothesof/tofu-feedstock

### PR DESCRIPTION
**Pull request by flothesof**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flothesof** [comment]
@conda-forge-admin, please rerender

**Comment by Didou09** [comment]
I don't see the answer of the re-rendering bot, we should for it before merging right ?

**Comment by Didou09** [comment]
Yes, so it did commit changes, but did not write a message here, I guess we can assume it is sufficient and we can merge, right?
What do you think ?

**Comment by flothesof** [comment]
Absolutely! It looks good to me!

**Pull request merged**
